pipeline {
  agent {
    label "agent"
  }

  stages {
    stage ("Hello"){
      steps {
        sh "java -version"
        echo "Getting working directory"
        sh "pwd"								
      }
    }
  }
}
